/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * NOTE: This file is typically generated by `npx convex dev`.
 * It is included in this repo so TypeScript type-checking works out of the box.
 * @module
 */

import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";

import type * as ResendOTP from "../ResendOTP.js";
import type * as ResendOTPPasswordReset from "../ResendOTPPasswordReset.js";
import type * as auth from "../auth.js";
import type * as blog from "../blog.js";
import type * as cases from "../cases.js";
import type * as contact from "../contact.js";
import type * as http from "../http.js";
import type * as products from "../products.js";
import type * as router from "../router.js";
import type * as userProfiles from "../userProfiles.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  ResendOTP: typeof ResendOTP;
  ResendOTPPasswordReset: typeof ResendOTPPasswordReset;
  auth: typeof auth;
  blog: typeof blog;
  cases: typeof cases;
  contact: typeof contact;
  http: typeof http;
  products: typeof products;
  router: typeof router;
  userProfiles: typeof userProfiles;
}>;

export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;
